pipeline{
    agent any
    environment {
            PIPELINE_NAME = "${env.JOB_NAME}"
    }
    stages{
        stage('Test'){
              agent {
                  docker {
                      image 'jelastic/maven:3.9.5-openjdk-21'
                      args '-v /root/.m2:/root/.m2'
                  }
              }
              steps{
                   sh 'mvn test -Dspring.profiles.active=test'
              }
        }
        stage('package'){
           agent {
                docker {
                    image 'jelastic/maven:3.9.5-openjdk-21'
                    args '-v /root/.m2:/root/.m2'
                }
           }
           steps{
            script {
                sh 'mvn -DskipTests clean package'
                sh 'cp -R target/ /var/jenkins_home/workspace/${PIPELINE_NAME}/target'
            }
           }
        }
        stage('Build'){
             steps{
                script {
                  sh 'docker build -t linktic/product-catalog-service .'
                }
             }
        }
        stage('Registry'){
             steps{
                script {
                  sh 'echo Se sube la imagen docker al servicio cluod utilizado'
                }
             }
        }
        stage('Deploy'){
             steps{
                script {
                  sh 'echo Se hace el despliegue del servicio con la estrategia que se defina en la infra'
                }
             }
        }
    }
}